//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodingFS.Test.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CodingFS.Test.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;project version=&quot;4&quot;&gt;
        ///  &lt;component name=&quot;ProjectModuleManager&quot;&gt;
        ///    &lt;modules&gt;
        ///      &lt;module fileurl=&quot;file://$PROJECT_DIR$/MyAudioPlayer.iml&quot; filepath=&quot;$PROJECT_DIR$/MyAudioPlayer.iml&quot; /&gt;
        ///      &lt;module fileurl=&quot;file://$PROJECT_DIR$/app/app.iml&quot; filepath=&quot;$PROJECT_DIR$/app/app.iml&quot; /&gt;
        ///    &lt;/modules&gt;
        ///  &lt;/component&gt;
        ///&lt;/project&gt; 的本地化字符串。
        /// </summary>
        internal static string modules {
            get {
                return ResourceManager.GetString("modules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;project version=&quot;4&quot;&gt;
        ///  &lt;component name=&quot;ChangeListManager&quot;&gt;
        ///    &lt;list default=&quot;true&quot; id=&quot;0a5b9100-98c1-479a-8536-1c416b5eb4d7&quot; name=&quot;Default Changelist&quot; comment=&quot;&quot; /&gt;
        ///    &lt;option name=&quot;EXCLUDED_CONVERTED_TO_IGNORED&quot; value=&quot;true&quot; /&gt;
        ///    &lt;option name=&quot;SHOW_DIALOG&quot; value=&quot;false&quot; /&gt;
        ///    &lt;option name=&quot;HIGHLIGHT_CONFLICTS&quot; value=&quot;true&quot; /&gt;
        ///    &lt;option name=&quot;HIGHLIGHT_NON_ACTIVE_CHANGELIST&quot; value=&quot;false&quot; /&gt;
        ///    &lt;option name=&quot;LAST_RESOLUTION&quot; value=&quot;IGNORE&quot; /&gt;
        ///  &lt;/component&gt;
        ///  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string workspace {
            get {
                return ResourceManager.GetString("workspace", resourceCulture);
            }
        }
    }
}
