# The starting directory to traverse, used in Mount and List command.
Root = "."

# Maximum search depth (include the root).
MaxDepth = 6

# Additional paths are considered to be dependency.
Deps = []

# Additional paths are considered to be generated.
Generated = [
	"C:\\foo\\bar",
	"C:\\some\\file",
]

# Options used in mounting vritual drive.
[Mount]

# Mount point, in Windows is the drive letter, Omitted to let CodingFS choose.
#Point = "X:"

# Which type of files should be included in the file system.
# Avaliable values: Source, Dependency, Generated, use comma to separate flags.
Type = "Source"

[Detector]

# Set the type of files matched by .gitignore, NotCare, Dependency, or Ignored.
Gitignore = "NotCare"
